;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-delete-forward
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        erlang-electric-lt
        evil-complete-previous
        evil-copy-from-below
        evil-insert
        evil-previous-line
        evil-yank
        ))

(setq mc/cmds-to-run-once
      '(
        describe-key
        evil-delete
        evil-next-line
        evil-search-next
        helm-gtags-pop-stack
        prelude-move-beginning-of-line
        ))
